from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.schemas.interview import InterviewStart, QuestionResponse, AnswerSubmit
from app.schemas.evaluation import AnswerEvaluation, EvaluationResult # Updated import
from app.ai.llm_client import evaluate_candidate_answer, generate_next_question # Updated import
from app.db.models.interview import InterviewSession, QuestionAnswer

async def start_new_interview(start_data: InterviewStart, db: AsyncSession) -> QuestionResponse:
    """
    Creates a new interview session in the DB, generates the first question, and saves it.
    """
    # 1. Create the Interview Session in the database
    new_session = InterviewSession(
        role=start_data.role, 
        experience_level=start_data.experience_level
    )
    db.add(new_session)
    await db.flush() # Flush generates the ID without permanently committing yet

    # 2. Generate the first question (Later, we'll use AI for this too)
    tech = start_data.tech_stack[0] if start_data.tech_stack else "your core technology"
    question_text = f"Welcome. As a {start_data.experience_level} {start_data.role}, can you explain your experience with {tech}, and give an example of a challenging problem you solved using it?"

    # 3. Save the question to the database linked to our new session
    new_question = QuestionAnswer(
        session_id=new_session.id,
        question_text=question_text,
        difficulty="Medium"
    )
    db.add(new_question)
    
    # 4. Commit everything to the hard drive
    await db.commit()
    await db.refresh(new_session) 
    await db.refresh(new_question) # Loads the final ID generated by the database

    return QuestionResponse(
        question_id=new_question.id,
        text=new_question.question_text,
        difficulty=new_question.difficulty,
        session_id=new_session.id
    )

async def process_answer(answer_data: AnswerSubmit, db: AsyncSession) -> EvaluationResult:
    """
    Fetches the question from the DB, grades the answer via AI, generates the NEXT question, and saves everything.
    """
    # 1. Look up the specific question the user is answering
    result = await db.execute(select(QuestionAnswer).where(QuestionAnswer.id == answer_data.question_id))
    db_question = result.scalars().first()
    
    if not db_question:
        raise ValueError("Question not found in database.")

    # 2. Look up the session to get the role and experience level
    session_result = await db.execute(select(InterviewSession).where(InterviewSession.id == db_question.session_id))
    db_session = session_result.scalars().first()

    # 3. Call our AI Engine to grade the answer
    evaluation = await evaluate_candidate_answer(
        role=db_session.role,
        experience_level=db_session.experience_level,
        question=db_question.question_text,
        candidate_answer=answer_data.answer_text
    )
    
    # 4. Save the user's answer and the AI's grade back to the database
    db_question.user_answer = answer_data.answer_text
    db_question.ai_score = evaluation.score
    db_question.ai_feedback = evaluation.feedback

    # 5. Call AI Engine 2: Generate the NEXT Question
    next_q_gen = await generate_next_question(
        role=db_session.role,
        experience_level=db_session.experience_level,
        previous_question=db_question.question_text,
        score=evaluation.score,
        weaknesses=evaluation.weaknesses

    )
    
    # 6. Save the NEW queation to the database so it's ready for the user's next turn
    new_db_question = QuestionAnswer(
        session_id=db_session.id,
        question_text=next_q_gen.next_question,
        difficulty=next_q_gen.difficulty
    )
    db.add(new_db_question)

    # commit everything to the hard drive

    await db.commit()
    await db.refresh(new_db_question) # Fetches the new question_id from the DB
    
    #7. Attach the newly generated database ID to the AI's response
    next_q_gen.question_id = new_db_question.id


    return EvaluationResult(
        evaluation=evaluation,
        next_question=next_q_gen
    )

async def generate_final_report(session_id: int, db: AsyncSession):
    """
    Dynamically calculates the final score by averaging all answered questions 
    in the session and builds the performance profile.
    """
    # 1. Fetch the session info
    session_result = await db.execute(select(InterviewSession).where(InterviewSession.id == session_id))
    db_session = session_result.scalars().first()
    
    if not db_session:
        raise ValueError("Interview session not found.")

    # 2. Fetch all completed question/answer records for this specific session
    result = await db.execute(
        select(QuestionAnswer).where(
            QuestionAnswer.session_id == session_id,
            QuestionAnswer.user_answer.isnot(None) # Only count answered questions!
        )
    )
    answered_questions = result.scalars().all()

    # 3. Handle edge case: User clicked finish without answering anything
    if not answered_questions:
        return {
            "final_score": 0.0,
            "summary": "No questions were answered during this session.",
            "top_strengths": ["N/A"],
            "top_weaknesses": ["Session wrapped up early."],
            "recommended_study_topics": ["Try answering at least one question next time!"]
        }

    # 4. 🔥 DYNAMIC MATH: Sum all AI scores and calculate the real average
    total_score = sum([q.ai_score for q in answered_questions if q.ai_score is not None])
    calculated_average = round(total_score / len(answered_questions), 1)

    # 5. Extract strengths and weaknesses from the AI feedback
    # (For a quick implementation, we will use dynamic placeholders based on the role, 
    # but the SCORE is 100% mathematically accurate based on your actual answers!)
    return {
        "final_score": calculated_average,
        "summary": f"The candidate completed a technical evaluation for the {db_session.role} position. Based on {len(answered_questions)} answered questions, they achieved an average score of {calculated_average}/10.",
        "top_strengths": [f"Knowledge of {db_session.role} concepts", "Handling technical follow-ups"],
        "top_weaknesses": ["Deep diving into edge cases", "Providing highly specific code examples"],
        "recommended_study_topics": ["Advanced architecture patterns", "System performance tuning"]
    }